[build]
  command = "npm run build && npm run export"
  publish = "out"
  environment = { NODE_VERSION = "16" } # Asegúrate de usar la versión que soporte Next.js si necesitas una específica.

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
